version: '3'

services:

  halumi:
    build:
      context: ./docker

    image: otolab/halumi-core

    environment:
      SERVER_MODE: "${HALUMI_CORE_MODE:-demo}"
      ACCESS_CONTROL_ALLOW_ORIGIN: "${HALUMI_CORE_ORIGIN:-http://localhost}"

    ports:
      - 80:8080

    volumes:
      - ${HAL_DIR:-./}:/home/ubuntu/halumi:delegated
      - knp-dict:/usr/local/share/knp
      - jumanpp-dict:/usr/local/share/jumanpp
      - global-node-modules:/usr/local/lib/node_modules
      - yarn-cache:/home/ubuntu/.cache/yarn

    cap_add:
      - SYS_TIME

volumes:
  jumanpp-dict:
  knp-dict:
  global-node-modules:
  yarn-cache:
