version: '3'

services:

  halumi:
    build:
      context: ./docker

    image: otolab/halumi-core

    environment:
      SERVER_MODE: "false"
      # ACCESS_CONTROL_ALLOW_ORIGIN: "tech.plaid.co.jp"

    ports:
      - 80:8080

    volumes:
      - ${HAL_DIR:-./}:/home/ubuntu/halumi:delegated
      - knp-dict:/usr/local/share/knp
      - juman-dict:/usr/local/share/juman
      - global-node-modules:/usr/local/lib/node_modules
      - yarn-cache:/home/ubuntu/.cache/yarn

    cap_add:
      - SYS_TIME

volumes:
  juman-dict:
  knp-dict:
  global-node-modules:
  yarn-cache:
